package com.ika.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;

/**
 * Dokumen generated by iRays
 */

@SuppressWarnings("serial")
@Entity
@Table(name="dokumen")
@Audited
public class Dokumen extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="SEQ_DOKUMEN")
	@SequenceGenerator(name="SEQ_DOKUMEN", sequenceName="SEQ_DOKUMEN", allocationSize=1)
	@Column(name="ID", unique=true, nullable=false)
	private Long id;
	
	@Length(max=100, message="{validator.long}")
	@Column(name="NAMA_DOKUMEN", length=100)
	private String namaDokumen;
	
	@Length(max=100, message="{validator.long}")
	@Column(name="FORMAT", length=100)
	private String format;
	
	@Column(name="SAIZ")
	private Long saiz;
	
	@Column(name="KANDUNGAN")
	private byte[] kandungan;

	public Dokumen() {
	}

	public Dokumen(Long id, String namaDokumen, String format, Long saiz,
			byte[] kandungan) {
		this.id = id;
		this.namaDokumen = namaDokumen;
		this.format = format;
		this.saiz = saiz;
		this.kandungan = kandungan;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNamaDokumen() {
		return this.namaDokumen;
	}

	public void setNamaDokumen(String namaDokumen) {
		this.namaDokumen = namaDokumen;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public Long getSaiz() {
		return this.saiz;
	}

	public void setSaiz(Long saiz) {
		this.saiz = saiz;
	}

	public byte[] getKandungan() {
		return this.kandungan;
	}

	public void setKandungan(byte[] kandungan) {
		this.kandungan = kandungan;
	}
}
