package com.ika.entity;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;



/**
 * Pengguna generated by iRays
 */

@SuppressWarnings("serial")
@Entity
@Table(name="keperluan")
@Audited
public class Keperluan  implements java.io.Serializable{
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="SEQ_KEPERLUAN")
	@SequenceGenerator(name="SEQ_KEPERLUAN", sequenceName="SEQ_KEPERLUAN", allocationSize=1)
	@Column(name="ID", unique=true, nullable=false)
	private Long id;
	
	@NotNull
	@Column(name="KOD")
	private Long kod;
	
	@NotNull
	@Length(max=500, message="{validator.long}")
	@Column(name="KENYATAAN", length=500)
	private String kenyataan;
	
	@NotNull
	@Column(name="TAHUN")
	private Long tahun;
	
	@NotNull
	@Column(name="HARGA_SEUNIT", precision=12, scale=2)
	private BigDecimal hargaSeunit;
	
	@NotNull
	@Column(name="HARGA_JUALAN", precision=12, scale=2)
	private BigDecimal hargaJualan;

	@NotNull
	@Length(max=1, message="{validator.long}")
	@Column(name="KATEGORI", length=1)
	private String kategori;
	
	public Keperluan(){
		
	}
	
	public Keperluan(Long id,Long kod,String kenyataan,Long tahun, BigDecimal hargaSeunit, BigDecimal hargaJualan, String kategori){
		this.id = id;
		this.kenyataan = kenyataan;	
		this.kod = kod;
		this.hargaJualan = hargaJualan;
		this.hargaSeunit = hargaSeunit;
		this.tahun = tahun;
		this.kategori = kategori;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKod() {
		return kod;
	}

	public void setKod(Long kod) {
		this.kod = kod;
	}

	public String getKenyataan() {
		return kenyataan;
	}

	public void setKenyataan(String kenyataan) {
		this.kenyataan = kenyataan;
	}

	public Long getTahun() {
		return tahun;
	}

	public void setTahun(Long tahun) {
		this.tahun = tahun;
	}

	public BigDecimal getHargaSeunit() {
		return hargaSeunit;
	}

	public void setHargaSeunit(BigDecimal hargaSeunit) {
		this.hargaSeunit = hargaSeunit;
	}

	public BigDecimal getHargaJualan() {
		return hargaJualan;
	}

	public void setHargaJualan(BigDecimal hargaJualan) {
		this.hargaJualan = hargaJualan;
	}

	public String getKategori() {
		return kategori;
	}

	public void setKategori(String kategori) {
		this.kategori = kategori;
	}
	
	
	
}
