package com.ika.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * KodKategoriPengguna generated by iRays
 */
@SuppressWarnings("serial")
@Entity
@Table(name="kod_kategori_pengguna")
@Audited
public class KodKategoriPengguna extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="SEQ_KODKATEGORIPENGGUNA")
	@SequenceGenerator(name="SEQ_KODKATEGORIPENGGUNA", sequenceName="SEQ_KODKATEGORIPENGGUNA", allocationSize=1)
	@Column(name="ID", unique=true, nullable=false)
	private Long id;
	
	@NotNull
	@Length(max=50, message="{validator.long}")
	@Column(name="PERIHAL", length=50)
	private String perihal;

	public KodKategoriPengguna() {
	}

	public KodKategoriPengguna(Long id, String perihal) {
		this.id = id;
		this.perihal = perihal;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPerihal() {
		return this.perihal;
	}

	public void setPerihal(String perihal) {
		this.perihal = perihal;
	}
}
